In [1]:
import folium
import time
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
df = pd.read_csv('./total.csv')
df

,Unnamed: 0,ts,action,actionOption,actionSub,actionSubOption,condition,conditionSub1Option,conditionSub2Option,place,...,rr_average,rr_min,rr_max,breathing_disturbances_intensity,snoring,snoringepisodecount,sleep_score,snoring.1,snoringepisodecount.1,sleep_score.1
0,0,2020_08_29_05_20_00_PM,work,212,NaN,NaN,WITH_MANY,5.0,2.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020_08_29_05_21_00_PM,work,212,NaN,NaN,WITH_MANY,5.0,2.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2020_08_29_05_22_00_PM,work,212,NaN,NaN,WITH_MANY,5.0,2.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2020_08_29_05_23_00_PM,work,212,NaN,NaN,WITH_MANY,5.0,2.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2020_08_29_05_24_00_PM,work,212,NaN,NaN,WITH_MANY,5.0,2.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21097,21097,2020_09_27_11_33_00_PM,recreation_media,722,NaN,NaN,WITH_ONE,2.0,2.0,home,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21098,21098,2020_09_27_11_34_00_PM,recreation_media,722,NaN,NaN,WITH_ONE,2.0,2.0,home,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21099,21099,2020_09_27_11_35_00_PM,recreation_media,722,NaN,NaN,WITH_ONE,2.0,2.0,home,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21100,21100,2020_09_27_11_49_00_PM,recreation_media,722,NaN,NaN,WITH_ONE,2.0,2.0,home,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21101,21101,2020_09_27_11_54_00_PM,recreation_media,722,NaN,NaN,WITH_ONE,2.0,2.0,home,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
times = df.index.tolist()
center = df[['mgps_lat_mean','mgps_lon_mean']].iloc[1].tolist()

In [4]:
x_y= pd.concat([df['mgps_lat_mean'],df['mgps_lon_mean']],axis=1)
x_y_ts= pd.concat([df['ts'],df['mgps_lat_mean'],df['mgps_lon_mean']],axis=1)

x_y_n=x_y.dropna()

In [5]:
df.loc[df['emotionPositive']>=6]['action']

25            travel
26            travel
27            travel
28            travel
29            travel
            ...
20939    outdoor_act
20940    outdoor_act
20941    outdoor_act
20942    outdoor_act
20943    outdoor_act
Name: action, Length: 10775, dtype: object

In [6]:
x_y_ts=x_y_ts.dropna()

In [7]:
x_y_ts['ts'].iloc[-1][8:10]

'27'

In [8]:
df[[ 'condition', 'conditionSub1Option','conditionSub2Option', 'place', 'emotionPositive', 'emotionTension',]].corr()

,conditionSub1Option,conditionSub2Option,emotionPositive,emotionTension
conditionSub1Option,1.000000,-0.533181,-0.258590,0.732289
conditionSub2Option,-0.533181,1.000000,0.536403,-0.414390
emotionPositive,-0.258590,0.536403,1.000000,-0.000828
emotionTension,0.732289,-0.414390,-0.000828,1.000000

In [9]:
df[df['place']=='other_indoor']

,Unnamed: 0,ts,action,actionOption,actionSub,actionSubOption,condition,conditionSub1Option,conditionSub2Option,place,...,rr_average,rr_min,rr_max,breathing_disturbances_intensity,snoring,snoringepisodecount,sleep_score,snoring.1,snoringepisodecount.1,sleep_score.1
0,0,2020_08_29_05_20_00_PM,work,212,NaN,NaN,WITH_MANY,5.0,2.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020_08_29_05_21_00_PM,work,212,NaN,NaN,WITH_MANY,5.0,2.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2020_08_29_05_22_00_PM,work,212,NaN,NaN,WITH_MANY,5.0,2.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2020_08_29_05_23_00_PM,work,212,NaN,NaN,WITH_MANY,5.0,2.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2020_08_29_05_24_00_PM,work,212,NaN,NaN,WITH_MANY,5.0,2.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18539,18539,2020_09_24_09_45_00_PM,outdoor_act,756,NaN,NaN,WITH_MANY,5.0,1.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18540,18540,2020_09_24_09_46_00_PM,outdoor_act,756,NaN,NaN,WITH_MANY,5.0,1.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18541,18541,2020_09_24_09_47_00_PM,outdoor_act,756,NaN,NaN,WITH_MANY,5.0,1.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18542,18542,2020_09_24_09_48_00_PM,outdoor_act,756,NaN,NaN,WITH_MANY,5.0,1.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18543,18543,2020_09_24_09_49_00_PM,outdoor_act,756,NaN,NaN,WITH_MANY,5.0,1.0,other_indoor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
x_y_n.folium()

AttributeError: 'DataFrame' object has no attribute 'folium'